### ISSUE TITLE
Wrong gitlab API url when using on-prem server

### ISSUE THREAD

**Issue by lithorus** [manland/mattermost-plugin-gitlab#1]
When using custom "Enterprise Base URL" it seems that it pre-pends api/v3 before the api/v4 url.

Getting this error when trying to authorize the plugin after `/gitlab connect`:

`GET https://gitlab.local.domain/api/v3/api/v4/user: 410 {error: API V3 is no longer supported. Use API V4 instead.}`

**Comment by jasonblais** [comment]
@manland This is likely remnants of the GitHub plugin, but may have been fixed since?

**Comment by manland** [comment]
@jasonblais yes it's fixed but I haven't push so I haven't close it! I'm on the last manual tests with local gitlab and all seems ok 😋 maybe tonight, maybe tomorrow I will push and release the first version!

**Comment by jasonblais** [comment]
Great to hear, thanks @manland 👍

**Comment by manland** [comment]
Will be included in the first version
