### ISSUE TITLE
Implement build web hook event

### ISSUE THREAD

**Issue by manland** [manland/mattermost-plugin-gitlab#12]

**Comment by hanzei** [comment]
Maybe post a message if a pipeline fails?

**Comment by manland** [comment]
Yes I have the same request for this plugin https://github.com/manland/mattermost-plugin-gitlab/pull/16/files#diff-f5423ed5cd60421ed7d6afba24d23d86R26 but i haven't a local runner on my local instance... In need to find a raw json of a failed pipeline to implement it!

I have created a separate issue to not forget https://github.com/manland/mattermost-plugin-gitlab/issues/17
