### ISSUE TITLE
Add screenshot in README.md

### ISSUE THREAD

**Issue by manland** [manland/mattermost-plugin-gitlab#26]

**Comment by jasonblais** [comment]
One option might be below, except for `Gitlab` --> `GitLab`

![image](https://user-images.githubusercontent.com/13119842/57229258-9fc11000-6fe3-11e9-9814-df01263ab294.png)

You can also see an example screenshot here https://github.com/mattermost/mattermost-plugin-github

**Comment by manland** [comment]
Not perfect but we can see left side bar

![Sélection_227](https://user-images.githubusercontent.com/1492516/57301593-afbb1b80-70d9-11e9-9134-809e5cc69a45.png)

When we will deploy one version on a real server, I will take a `real life` screenshot ;)

**Comment by jasonblais** [comment]
@manland Good point about showing the left hand sidebar. 

There's also a command line tool to load sample data to a Mattermost server: https://docs.mattermost.com/administration/command-line-tools.html#mattermost-sampledata
