### ISSUE TITLE
Error when connecting with gitlab

### ISSUE THREAD

**Issue by zegervdv** [manland/mattermost-plugin-gitlab#39]
Wheb running `/gitlab connect` and signing in I get the approval page to authorize access to my account.

After clicking on approve I get a page with only:
```
invalid character '<' looking for beginning of value
```
This is the error I see in the mattermost logs:
```
{"level":"error","ts":1557431585.4238338,"caller":"mlog/sugar.go:23","msg":"can't exchange state","plugin_id":"com.github.manland.mattermost-plugin-gitlab","err":"invalid character '<' looking for beginning of value"}
```

**Comment by manland** [comment]
Hi thanks to use this plugin!

I have tested on my local installation and all is ok. 

Could you look at your config ? This error happen when gitlab return an html (mostly due to error page or proxy config).

**Comment by zegervdv** [comment]
I started again from scratch but I still get the same error.
We do have a proxy on our network, is there a way to get some more debug info?

I also have configuration to sign in via Gitlab in the Mattermost client and that redirect works fine.

**Comment by zegervdv** [comment]
After restarting Mattermost it works now, not sure what fixed it :) 

Sorry for the disturbance and thanks for the plugin!

**Comment by manland** [comment]
Your welcome ;)
