### ISSUE TITLE
Help me with overstanding the ReadMe steps...

### ISSUE THREAD

**Issue by uhlhosting** [manland/mattermost-plugin-gitlab#46]
Unable to find this part nor any identical settings as described here:

I just realized now this is the old readme that applies to github mostly maybe thats why I do not find all menus like described ** updated **

**```
**Go to the settings page of your GitLab group and click on "Webhooks" in the sidebar
Click "Add webhook"** WHERE is this area Gitlab Group??? <=

Change content type to "application/json" <= Where is this? Maybe adding a Print screen visual or GIF or short video, very confusing this readme .

Select the events: Issues, Issue comments, Pull requests, Pull request reviews, Pull request review comments, Pushes, Branch or Tag creation and Branch or Tag deletion

<img width="981" alt="image" src="https://user-images.githubusercontent.com/6324047/57976065-11339200-79d8-11e9-84d0-66e2880f76dc.png">

I am curious where are your events taken from... Again confusing here while I could never match all events you described.

```**

**Comment by manland** [comment]
Hi!
Yes it's from the old github repo... I'm sorry.

In the next version you will not do this anymore #15 i'm finishing dev and test ;)

**Comment by manland** [comment]
I have rewritten the readme section of webhook https://github.com/manland/mattermost-plugin-gitlab#installation do you think its better ?

I think I will delay the `auto web-hook` feature after 0.3.0 because i need more time to test!

**Comment by uhlhosting** [comment]
@manland will try to give it a try to do a setup.

**Comment by uhlhosting** [comment]
I have managed to establish a connection!

**Comment by manland** [comment]
Thanks to close old issues :+1: :100:
