### ISSUE TITLE
Enable Private Repositories not enforced 

### ISSUE THREAD

**Issue by DHaussermann** [manland/mattermost-plugin-gitlab#52]
It it seems like even when `Enable Private Repositories` set to false, I can subscribe to private repos. I ensured that the plugin was restarted after the flag was set to False and saw the same result. 
**note**: It's possible this could just be incorrect feedback returned by the subscribe command  

1. Disable plugin
2. Set flag to false
3. Enable Plugin
4. Connect user to GitLab if needed - if needed
5. Subscribe to a private project in a private group ex:`/gitlab subscribe owner dkh-test-group/dkh-project2`
Expected: Subscription fails
Observed: Subscription was successful

**Comment by jasonblais** [comment]
Thanks! @manland Something to look into when you have time :)

**Comment by manland** [comment]
@jasonblais Yes i'm on it ;)

@DHaussermann with this command `/gitlab subscribe owner dkh-test-group/dkh-project2` you subscribe to the group `owner` with the feature `dkh-test-group/dkh-project2`. But I have found a bug if a group is private (`owner` in this case?) we can subscribe! I fix it. And with #47 and #22 all should be ok!

**Comment by jasonblais** [comment]
@manland You're awesome...thank you!! :tada:

**Comment by DHaussermann** [comment]
Oops Thanks @manland  good catch. I must have mistakenly left `owner` in there. 
And with #47, they'll be better validation for the user to catch a mistake like that :)
